// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package transport

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserSearcherClient is the client API for UserSearcher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserSearcherClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type userSearcherClient struct {
	cc grpc.ClientConnInterface
}

func NewUserSearcherClient(cc grpc.ClientConnInterface) UserSearcherClient {
	return &userSearcherClient{cc}
}

func (c *userSearcherClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/UserSearcher/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserSearcherServer is the server API for UserSearcher service.
// All implementations must embed UnimplementedUserSearcherServer
// for forward compatibility
type UserSearcherServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	mustEmbedUnimplementedUserSearcherServer()
}

// UnimplementedUserSearcherServer must be embedded to have forward compatible implementations.
type UnimplementedUserSearcherServer struct {
}

func (UnimplementedUserSearcherServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedUserSearcherServer) mustEmbedUnimplementedUserSearcherServer() {}

// UnsafeUserSearcherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserSearcherServer will
// result in compilation errors.
type UnsafeUserSearcherServer interface {
	mustEmbedUnimplementedUserSearcherServer()
}

func RegisterUserSearcherServer(s grpc.ServiceRegistrar, srv UserSearcherServer) {
	s.RegisterService(&UserSearcher_ServiceDesc, srv)
}

func _UserSearcher_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSearcherServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserSearcher/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSearcherServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserSearcher_ServiceDesc is the grpc.ServiceDesc for UserSearcher service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserSearcher_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "UserSearcher",
	HandlerType: (*UserSearcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _UserSearcher_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "messages.proto",
}
